application: tic-toolkit
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: django
  version: 1.2

handlers:  
- url: /stats.*
  script: google.appengine.ext.appstats.ui.app
 
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.application
  login: admin

- url: /_ah/mail/.+ 
  script: tic.web.boot.app
  login: admin

- url: .*
  script: tic.web.boot.app
 