application: nanosnecommerce
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
 
- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /_ah/mail/.+ 
  script: boot.py
  login: admin

- url: /media
  static_dir: media
  
- url: .*
  script: boot.py


skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(media/js/dojo/.*)
- ^(media/js/dijit/.*)
- ^(media/js/dojox/.*)
- ^(media/js/utils/.*)
    
